<div>
    <ul>
        <ul>
            <li>投稿者名</li>
            <li>投稿者名を入力</li>
        </ul>
        <ul>
            <li>タイトル</li>
            <li>タイトルを入力</li>
        </ul>
        <ul>
            <li>タグ</li>
            <li>タグを選択</li>
        </ul>
    </ul>
</div>